name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Bot name
        run: echo "My BOT_NAME is ${{secrets.BOT_NAME}}"
      - name: Bot token
        run: echo "My BOT_TOKEN is ${{secrets.BOT_TOKEN}}"
      - name: Bot chat id
        run: echo "My BOT_CHAT_ID is ${{secrets.BOT_CHAT_ID}}"

